version: '3.8'
services:
  app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongo:27017/myDatabase
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mi_red

  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mi_red

volumes:
  mongo-data:

networks:
  mi_red:
    driver: bridge
